### ISSUE TITLE
Bug: When changing time range for country with space in name, page resets

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#707]
When selecting a different date range, the current query is lost:

![2023-02-09 13 42 18](https://user-images.githubusercontent.com/25161793/217815943-aa852abc-75c0-41ab-b750-b9eff9646ae0.gif)

I could reproduce on Firefox. But somehow it may be country specific: Switzerland works. Maybe something about spaces again?

Seems to be regression of https://github.com/GenSpectrum/cov-spectrum-website/issues/704 and https://github.com/GenSpectrum/cov-spectrum-website/issues/694

**Comment by corneliusroemer** [comment]
Weird, wasn't https://github.com/GenSpectrum/cov-spectrum-website/pull/706 supposed to fix this?

**Comment by corneliusroemer** [comment]
Ah I see, this is a slightly different variation of the same bug: rather than country switching, I'm doing time switching here :)

**Comment by corneliusroemer** [comment]
I'm getting the following console error with it:

```console
selectors-from-explore-url-hook.ts:26 Uncaught TypeError: Cannot read properties of undefined (reading 'variants')
    at ine (selectors-from-explore-url-hook.ts:26:35)
    at Hbe (FocusPage.tsx:28:37)
    at Ta (react-dom.production.min.js:167:137)
    at wl (react-dom.production.min.js:197:258)
    at bs (react-dom.production.min.js:292:88)
    at vu (react-dom.production.min.js:280:389)
    at pu (react-dom.production.min.js:280:320)
    at du (react-dom.production.min.js:280:180)
    at ou (react-dom.production.min.js:273:245)
    at Lo (react-dom.production.min.js:127:105)
    at au (react-dom.production.min.js:274:266)
    at Pe (react-dom.production.min.js:52:423)
    at Fr (react-dom.production.min.js:109:469)
    at Yt (react-dom.production.min.js:74:59)
    at Ut (react-dom.production.min.js:73:73)
    at HTMLDivElement.o (helpers.ts:98:1)
```
