### ISSUE TITLE
EDIT: Resolved as soon as I submitted this -- All queries fail

### ISSUE THREAD

**Issue by Sinickle** [GenSpectrum/cov-spectrum-website#943]
EDIT: This was a temporary issue and is working for me again. Feel free to close if this doesn't seem important. 

I believe this started for me sometime between March 7 16:45 EST and 17:15 EST. 

All queries, having tried on both a PC and phone, result in the loading icon running forever. The UI stays in tact and is interactive though. 
![image](https://github.com/GenSpectrum/cov-spectrum-website/assets/94097102/a91b0504-69b0-426c-a9ba-cb90ce3dad63)

![image](https://github.com/GenSpectrum/cov-spectrum-website/assets/94097102/5e0676e2-6f07-4730-a11d-67ce8f653e2b)
Failed to load resource: the server responded with a status of 503 ()
instrument.ts:124 Error: Error fetching info
    at api-lapis.ts:83:11
    at p (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at o (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:22:9)
(anonymous) @ instrument.ts:124
Show 1 more frame
Show less
2instrument.ts:124 DOMException: The user aborted a request.

**Comment by chaoran-chen** [comment]
Thank you very much for the report! It seems to be the time when we updated the data but it is not supposed to cause any interruptions. We'll check this out!

**Comment by Sinickle** [comment]
![image](https://github.com/GenSpectrum/cov-spectrum-website/assets/94097102/62ef217f-97f1-43f1-a412-2b930457c5f4)

Happening again, March 14 19:50 EST

**Comment by fengelniederhammer** [comment]
@Sinickle could you please report again if it happens? It should be fixed now though.

**Comment by chaoran-chen** [comment]
I am just observing the same error as well:

<img width="1425" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/18666552/81879c57-9ffd-45e3-a4c8-20bc929c83f5">
